#!/bin/bash -x
# File: "/etc/pm/sleep.d/99_wifi".
case "${1}" in
        hibernate)
		/sbin/rmmod iwlmvm 
		/sbin/rmmod iwlwifi
                ;;
	resume|thaw)
		/sbin/modprobe iwlwifi
                /usr/sbin/service network-manager restart
		;;
esac
exit 0
